### ISSUE TITLE
Handy OMS CLI files executables are gone in 'a-new-dawn'

### ISSUE THREAD

**Issue by wilzbach** [microservices/oms#300]
https://github.com/microservices/oms/blob/master/oms

See also: https://github.com/microservices/oms/issues/298

**Comment by wilzbach** [comment]
Another service: https://github.com/oms-services/nexmo/pull/3

**Comment by StoryscriptHuman** [comment]
I am not sure I understand this. The file you have linked to did nothing but require another file, what I've done now is point manifest at root workspace package to same file, see https://github.com/microservices/oms/blob/df5ca63fa8633e0185a48a26f5cdca49b8080b25/package.json#L3

Keeping in mind that the file linked was a utility file, available only inside the meta package inside repository root and never published to npm that required a bin file of the npm package, I think we should rely on `yarn link` instead of running files directly

**Comment by wilzbach** [comment]
> Another service: oms-services/nexmo#3

This belonged to the wrong issue. It should have been https://github.com/microservices/oms/issues/302.

> I am not sure I understand this. The file you have linked to did nothing but require another file

I know, but it makes using the package easy for development / local checkout as you don't need `npx`, but can simply just do `./oms <commands>`

> Keeping in mind that the file linked was a utility file, available only inside the meta package inside repository root 

Yeah it's only for development convenience.
Though there's still https://github.com/microservices/oms/blob/a-new-dawn/tests/regression/bin/omg ;-)

>  I think we should rely on yarn link instead of running files directly

This requires people to add `~/.config/yarn/link` to their `PATH`.

I don't feel strongly about this, but apparently other people used it as well for development and there are no downsides, so you might as well add it back ;-)

**Comment by StoryscriptHuman** [comment]
> This requires people to add ~/.config/yarn/link to their PATH.

This is done by default on all non-manual NodeJS/Yarn installations! If it wasn't configured this way on your system, please double-check how you installed Yarn (installing with `npm install -g yarn` is highly-highly unrecommended, there's bash scripts and homebrew recipies for it you can try tho).

Regardless, this has been added to repository master, so gonna close this issue :)
